#pragma once
#include "SDE/ChemistryRuntime.hpp"

/**
 *  @file NWXDefaults.hpp
 *
 *  This file contains routines for generating the default initial chemical
 *  runtime state used by the NWX project.
 *
 *  @par Implementation Notes:
 *  - The definitions of all of these functions are generated by the scripts in
 *    the reference_data directory of SDE.
 *  - The sources for these functions are long, hard-coded tables, and as such
 *    each function is defined within its own source.
 *  - The sources for these functions live in the Defaults directory
 */
namespace SDE {

/// Returns a map of default constants
typename ChemistryRuntime::constant_lut_type default_constants();

/// Returns a map of default molecules
Utilities::CaseInsensitiveMap<LibChemist::Molecule> default_molecules();

/// Returns a map of default basis sets
std::map<std::size_t, LibChemist::Atom> default_bases();

/// Returns a map of default elemental properties
typename ChemistryRuntime::indexed_atom_type default_atoms();

/// Returns a map of known isotopes
typename ChemistryRuntime::isotope_lut_type default_isotopes();

/// Returns a map of symbols to atoms
typename ChemistryRuntime::at_sym_lut_type default_symbols();

/// Returns a map of angular momentum symbols to number values
typename ChemistryRuntime::am_sym_lut_type default_am();

/// Convenience function for making a fully defaulted ChemistryRuntime instance
inline ChemistryRuntime default_runtime() {
    return {default_constants(), default_atoms(), default_isotopes(),
            default_symbols(), default_am()};
}

} // End namespace SDE
