#pragma once

#include "hdf5_archive.hpp"
#include "cereal/archives/json.hpp"
#include "cereal/archives/xml.hpp"

#include "cereal/types/array.hpp"
#include "cereal/types/bitset.hpp"
#include "cereal/types/map.hpp"
#include "cereal/types/list.hpp"
#include "cereal/types/functional.hpp"
#include "cereal/types/forward_list.hpp"
#include "cereal/types/deque.hpp"
#include "cereal/types/complex.hpp"
#include "cereal/types/common.hpp"
#include "cereal/types/chrono.hpp"
#include "cereal/types/valarray.hpp"
#include "cereal/types/utility.hpp"
#include "cereal/types/unordered_set.hpp"
#include "cereal/types/unordered_map.hpp"
#include "cereal/types/tuple.hpp"
#include "cereal/types/string.hpp"
#include "cereal/types/stack.hpp"
#include "cereal/types/set.hpp"
#include "cereal/types/queue.hpp"
#include "cereal/types/polymorphic.hpp"
#include "cereal/types/memory.hpp"
#include "cereal/types/vector.hpp"
