#include "SDE/NWXDefaults.hpp"
/* Warning!!!! 
 * This file was auto-generated by generate_atomicinfo.py and should not be
 * modified.  To make modifications to this file please edit
 * generate_atomicinfo.py and regenerate this file.
 */
namespace SDE {
using return_t = typename ChemistryRuntime::indexed_atom_type;
return_t default_atoms() {
    return_t rv;
    rv[1] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 1},
      {LibChemist::Atom::Property::mass, 1.007975},
      {LibChemist::Atom::Property::cov_radius, 0.5858150988919267},
      {LibChemist::Atom::Property::vdw_radius, 2.267671350549394}
    }};
    rv[10] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 10},
      {LibChemist::Atom::Property::mass, 20.1797},
      {LibChemist::Atom::Property::cov_radius, 1.0960411527655403},
      {LibChemist::Atom::Property::vdw_radius, 2.9101782332050554}
    }};
    rv[100] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 100},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[101] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 101},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[102] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 102},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[103] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 103},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[104] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 104},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[105] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 105},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[106] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 106},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[107] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 107},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[108] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 108},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[109] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 109},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[11] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 11},
      {LibChemist::Atom::Property::mass, 22.98976928},
      {LibChemist::Atom::Property::cov_radius, 3.136945368259995},
      {LibChemist::Atom::Property::vdw_radius, 4.28967830478927}
    }};
    rv[110] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 110},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[111] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 111},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[112] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 112},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[113] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 113},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[114] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 114},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[115] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 115},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[116] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 116},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[117] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 117},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[118] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 118},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[12] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 12},
      {LibChemist::Atom::Property::mass, 24.3055},
      {LibChemist::Atom::Property::cov_radius, 2.6645138368955377},
      {LibChemist::Atom::Property::vdw_radius, 3.2692261970420424}
    }};
    rv[13] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 13},
      {LibChemist::Atom::Property::mass, 26.9815385},
      {LibChemist::Atom::Property::cov_radius, 2.286568611803972},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[14] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 14},
      {LibChemist::Atom::Property::mass, 28.085},
      {LibChemist::Atom::Property::cov_radius, 2.097595999258189},
      {LibChemist::Atom::Property::vdw_radius, 3.968424863461439}
    }};
    rv[15] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 15},
      {LibChemist::Atom::Property::mass, 30.973761998},
      {LibChemist::Atom::Property::cov_radius, 2.022006954239876},
      {LibChemist::Atom::Property::vdw_radius, 3.4015070258240905}
    }};
    rv[16] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 16},
      {LibChemist::Atom::Property::mass, 32.0675},
      {LibChemist::Atom::Property::cov_radius, 1.9842124317307195},
      {LibChemist::Atom::Property::vdw_radius, 3.4015070258240905}
    }};
    rv[17] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 17},
      {LibChemist::Atom::Property::mass, 35.4515},
      {LibChemist::Atom::Property::cov_radius, 1.9275206479669846},
      {LibChemist::Atom::Property::vdw_radius, 3.307020719551199}
    }};
    rv[18] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 18},
      {LibChemist::Atom::Property::mass, 39.948},
      {LibChemist::Atom::Property::cov_radius, 2.003109692985298},
      {LibChemist::Atom::Property::vdw_radius, 3.552685115860717}
    }};
    rv[19] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 19},
      {LibChemist::Atom::Property::mass, 39.0983},
      {LibChemist::Atom::Property::cov_radius, 3.836144034679391},
      {LibChemist::Atom::Property::vdw_radius, 5.196746845009027}
    }};
    rv[2] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 2},
      {LibChemist::Atom::Property::mass, 4.002602},
      {LibChemist::Atom::Property::cov_radius, 0.5291233151281919},
      {LibChemist::Atom::Property::vdw_radius, 2.6456165756409593}
    }};
    rv[20] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 20},
      {LibChemist::Atom::Property::mass, 40.078},
      {LibChemist::Atom::Property::cov_radius, 3.3259179808057775},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[21] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 21},
      {LibChemist::Atom::Property::mass, 44.955908},
      {LibChemist::Atom::Property::cov_radius, 3.212534413278308},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[22] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 22},
      {LibChemist::Atom::Property::mass, 47.867},
      {LibChemist::Atom::Property::cov_radius, 3.023561800732525},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[23] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 23},
      {LibChemist::Atom::Property::mass, 50.9415},
      {LibChemist::Atom::Property::cov_radius, 2.891280971950477},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[24] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 24},
      {LibChemist::Atom::Property::mass, 51.9961},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[25] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 25},
      {LibChemist::Atom::Property::mass, 54.938044},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[26] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 26},
      {LibChemist::Atom::Property::mass, 55.845},
      {LibChemist::Atom::Property::cov_radius, 2.494438485604333},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[27] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 27},
      {LibChemist::Atom::Property::mass, 58.933194},
      {LibChemist::Atom::Property::cov_radius, 2.381054918076863},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[28] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 28},
      {LibChemist::Atom::Property::mass, 58.6934},
      {LibChemist::Atom::Property::cov_radius, 2.343260395567707},
      {LibChemist::Atom::Property::vdw_radius, 3.0802535844962597}
    }};
    rv[29] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 29},
      {LibChemist::Atom::Property::mass, 63.546},
      {LibChemist::Atom::Property::cov_radius, 2.494438485604333},
      {LibChemist::Atom::Property::vdw_radius, 2.6456165756409593}
    }};
    rv[3] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 3},
      {LibChemist::Atom::Property::mass, 6.9675},
      {LibChemist::Atom::Property::cov_radius, 2.41884944058602},
      {LibChemist::Atom::Property::vdw_radius, 3.439301548333247}
    }};
    rv[30] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 30},
      {LibChemist::Atom::Property::mass, 65.38},
      {LibChemist::Atom::Property::cov_radius, 2.30546587305855},
      {LibChemist::Atom::Property::vdw_radius, 2.626719314386381}
    }};
    rv[31] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 31},
      {LibChemist::Atom::Property::mass, 69.723},
      {LibChemist::Atom::Property::cov_radius, 2.30546587305855},
      {LibChemist::Atom::Property::vdw_radius, 3.5337878546061385}
    }};
    rv[32] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 32},
      {LibChemist::Atom::Property::mass, 72.63},
      {LibChemist::Atom::Property::cov_radius, 2.267671350549394},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[33] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 33},
      {LibChemist::Atom::Property::mass, 74.921595},
      {LibChemist::Atom::Property::cov_radius, 2.2487740892948156},
      {LibChemist::Atom::Property::vdw_radius, 3.495993332096982}
    }};
    rv[34] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 34},
      {LibChemist::Atom::Property::mass, 78.971},
      {LibChemist::Atom::Property::cov_radius, 2.267671350549394},
      {LibChemist::Atom::Property::vdw_radius, 3.5904796383698736}
    }};
    rv[35] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 35},
      {LibChemist::Atom::Property::mass, 79.904},
      {LibChemist::Atom::Property::cov_radius, 2.267671350549394},
      {LibChemist::Atom::Property::vdw_radius, 3.495993332096982}
    }};
    rv[36] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 36},
      {LibChemist::Atom::Property::mass, 83.798},
      {LibChemist::Atom::Property::cov_radius, 2.1920823055310805},
      {LibChemist::Atom::Property::vdw_radius, 3.817246773424813}
    }};
    rv[37] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 37},
      {LibChemist::Atom::Property::mass, 85.4678},
      {LibChemist::Atom::Property::cov_radius, 4.157397476007222},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[38] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 38},
      {LibChemist::Atom::Property::mass, 87.62},
      {LibChemist::Atom::Property::cov_radius, 3.684965944642765},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[39] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 39},
      {LibChemist::Atom::Property::mass, 88.90584},
      {LibChemist::Atom::Property::cov_radius, 3.5904796383698736},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[4] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 4},
      {LibChemist::Atom::Property::mass, 9.0121831},
      {LibChemist::Atom::Property::cov_radius, 1.814137080439515},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[40] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 40},
      {LibChemist::Atom::Property::mass, 91.224},
      {LibChemist::Atom::Property::cov_radius, 3.307020719551199},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[41] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 41},
      {LibChemist::Atom::Property::mass, 92.90637},
      {LibChemist::Atom::Property::cov_radius, 3.099150845750838},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[42] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 42},
      {LibChemist::Atom::Property::mass, 95.95},
      {LibChemist::Atom::Property::cov_radius, 2.9101782332050554},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[43] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 43},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 2.7778974044230074},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[44] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 44},
      {LibChemist::Atom::Property::mass, 101.07},
      {LibChemist::Atom::Property::cov_radius, 2.759000143168429},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[45] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 45},
      {LibChemist::Atom::Property::mass, 102.9055},
      {LibChemist::Atom::Property::cov_radius, 2.683411098150116},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[46] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 46},
      {LibChemist::Atom::Property::mass, 106.42},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 3.0802535844962597}
    }};
    rv[47] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 47},
      {LibChemist::Atom::Property::mass, 107.8682},
      {LibChemist::Atom::Property::cov_radius, 2.7401028819138507},
      {LibChemist::Atom::Property::vdw_radius, 3.2503289357874645}
    }};
    rv[48] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 48},
      {LibChemist::Atom::Property::mass, 112.414},
      {LibChemist::Atom::Property::cov_radius, 2.7212056206592723},
      {LibChemist::Atom::Property::vdw_radius, 2.9857672782233684}
    }};
    rv[49] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 49},
      {LibChemist::Atom::Property::mass, 114.818},
      {LibChemist::Atom::Property::cov_radius, 2.683411098150116},
      {LibChemist::Atom::Property::vdw_radius, 3.6471714221336082}
    }};
    rv[5] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 5},
      {LibChemist::Atom::Property::mass, 10.8135},
      {LibChemist::Atom::Property::cov_radius, 1.606267206639154},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[50] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 50},
      {LibChemist::Atom::Property::mass, 118.71},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 4.100705692243487}
    }};
    rv[51] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 51},
      {LibChemist::Atom::Property::mass, 121.76},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[52] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 52},
      {LibChemist::Atom::Property::mass, 127.6},
      {LibChemist::Atom::Property::cov_radius, 2.6078220531318026},
      {LibChemist::Atom::Property::vdw_radius, 3.892835818443126}
    }};
    rv[53] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 53},
      {LibChemist::Atom::Property::mass, 126.90447},
      {LibChemist::Atom::Property::cov_radius, 2.626719314386381},
      {LibChemist::Atom::Property::vdw_radius, 3.7416577284064996}
    }};
    rv[54] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 54},
      {LibChemist::Atom::Property::mass, 131.293},
      {LibChemist::Atom::Property::cov_radius, 2.6456165756409593},
      {LibChemist::Atom::Property::vdw_radius, 4.081808430988909}
    }};
    rv[55] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 55},
      {LibChemist::Atom::Property::mass, 132.90545196},
      {LibChemist::Atom::Property::cov_radius, 4.6109317461171},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[56] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 56},
      {LibChemist::Atom::Property::mass, 137.327},
      {LibChemist::Atom::Property::cov_radius, 4.06291116973433},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[57] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 57},
      {LibChemist::Atom::Property::mass, 138.90547},
      {LibChemist::Atom::Property::cov_radius, 3.9117330796977043},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[58] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 58},
      {LibChemist::Atom::Property::mass, 140.116},
      {LibChemist::Atom::Property::cov_radius, 3.8550412959339693},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[59] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 59},
      {LibChemist::Atom::Property::mass, 140.90766},
      {LibChemist::Atom::Property::cov_radius, 3.836144034679391},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[6] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 6},
      {LibChemist::Atom::Property::mass, 12.0106},
      {LibChemist::Atom::Property::cov_radius, 1.4361918553479494},
      {LibChemist::Atom::Property::vdw_radius, 3.212534413278308}
    }};
    rv[60] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 60},
      {LibChemist::Atom::Property::mass, 144.242},
      {LibChemist::Atom::Property::cov_radius, 3.7983495121702346},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[61] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 61},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 3.760554989661078},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[62] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 62},
      {LibChemist::Atom::Property::mass, 150.36},
      {LibChemist::Atom::Property::cov_radius, 3.7416577284064996},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[63] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 63},
      {LibChemist::Atom::Property::mass, 151.964},
      {LibChemist::Atom::Property::cov_radius, 3.7416577284064996},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[64] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 64},
      {LibChemist::Atom::Property::mass, 157.25},
      {LibChemist::Atom::Property::cov_radius, 3.7038632058973433},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[65] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 65},
      {LibChemist::Atom::Property::mass, 158.92535},
      {LibChemist::Atom::Property::cov_radius, 3.6660686833881866},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[66] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 66},
      {LibChemist::Atom::Property::mass, 162.5},
      {LibChemist::Atom::Property::cov_radius, 3.62827416087903},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[67] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 67},
      {LibChemist::Atom::Property::mass, 164.93033},
      {LibChemist::Atom::Property::cov_radius, 3.62827416087903},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[68] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 68},
      {LibChemist::Atom::Property::mass, 167.259},
      {LibChemist::Atom::Property::cov_radius, 3.5715823771152952},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[69] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 69},
      {LibChemist::Atom::Property::mass, 168.93422},
      {LibChemist::Atom::Property::cov_radius, 3.5904796383698736},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[7] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 7},
      {LibChemist::Atom::Property::mass, 14.006855},
      {LibChemist::Atom::Property::cov_radius, 1.341705549075058},
      {LibChemist::Atom::Property::vdw_radius, 2.9290754944596338}
    }};
    rv[70] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 70},
      {LibChemist::Atom::Property::mass, 173.045},
      {LibChemist::Atom::Property::cov_radius, 3.5337878546061385},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[71] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 71},
      {LibChemist::Atom::Property::mass, 174.9668},
      {LibChemist::Atom::Property::cov_radius, 3.5337878546061385},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[72] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 72},
      {LibChemist::Atom::Property::mass, 178.49},
      {LibChemist::Atom::Property::cov_radius, 3.307020719551199},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[73] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 73},
      {LibChemist::Atom::Property::mass, 180.94788},
      {LibChemist::Atom::Property::cov_radius, 3.212534413278308},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[74] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 74},
      {LibChemist::Atom::Property::mass, 183.84},
      {LibChemist::Atom::Property::cov_radius, 3.0613563232416814},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[75] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 75},
      {LibChemist::Atom::Property::mass, 186.207},
      {LibChemist::Atom::Property::cov_radius, 2.8534864494413203},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[76] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 76},
      {LibChemist::Atom::Property::mass, 190.23},
      {LibChemist::Atom::Property::cov_radius, 2.7212056206592723},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[77] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 77},
      {LibChemist::Atom::Property::mass, 192.217},
      {LibChemist::Atom::Property::cov_radius, 2.6645138368955377},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[78] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 78},
      {LibChemist::Atom::Property::mass, 195.084},
      {LibChemist::Atom::Property::cov_radius, 2.5700275306226463},
      {LibChemist::Atom::Property::vdw_radius, 3.307020719551199}
    }};
    rv[79] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 79},
      {LibChemist::Atom::Property::mass, 196.966569},
      {LibChemist::Atom::Property::cov_radius, 2.5700275306226463},
      {LibChemist::Atom::Property::vdw_radius, 3.136945368259995}
    }};
    rv[8] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 8},
      {LibChemist::Atom::Property::mass, 15.9994},
      {LibChemist::Atom::Property::cov_radius, 1.2472192428021665},
      {LibChemist::Atom::Property::vdw_radius, 2.8723837106958987}
    }};
    rv[80] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 80},
      {LibChemist::Atom::Property::mass, 200.592},
      {LibChemist::Atom::Property::cov_radius, 2.494438485604333},
      {LibChemist::Atom::Property::vdw_radius, 2.9290754944596338}
    }};
    rv[81] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 81},
      {LibChemist::Atom::Property::mass, 204.3835},
      {LibChemist::Atom::Property::cov_radius, 2.7401028819138507},
      {LibChemist::Atom::Property::vdw_radius, 3.7038632058973433}
    }};
    rv[82] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 82},
      {LibChemist::Atom::Property::mass, 207.2},
      {LibChemist::Atom::Property::cov_radius, 2.759000143168429},
      {LibChemist::Atom::Property::vdw_radius, 3.817246773424813}
    }};
    rv[83] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 83},
      {LibChemist::Atom::Property::mass, 208.9804},
      {LibChemist::Atom::Property::cov_radius, 2.7967946656775857},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[84] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 84},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 2.6456165756409593},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[85] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 85},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 2.834589188186742},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[86] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 86},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 2.834589188186742},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[87] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 87},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 4.913287926190353},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[88] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 88},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 4.1762947372618004},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[89] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 89},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 4.06291116973433},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[9] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 9},
      {LibChemist::Atom::Property::mass, 18.998403163},
      {LibChemist::Atom::Property::cov_radius, 1.0771438915109621},
      {LibChemist::Atom::Property::vdw_radius, 2.7778974044230074}
    }};
    rv[90] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 90},
      {LibChemist::Atom::Property::mass, 232.0377},
      {LibChemist::Atom::Property::cov_radius, 3.892835818443126},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[91] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 91},
      {LibChemist::Atom::Property::mass, 231.03588},
      {LibChemist::Atom::Property::cov_radius, 3.7794522509156563},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[92] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 92},
      {LibChemist::Atom::Property::mass, 238.02891},
      {LibChemist::Atom::Property::cov_radius, 3.7038632058973433},
      {LibChemist::Atom::Property::vdw_radius, 3.51489059335156}
    }};
    rv[93] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 93},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 3.5904796383698736},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[94] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 94},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 3.5337878546061385},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[95] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 95},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 3.4015070258240905},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[96] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 96},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 3.1936371520237294},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[97] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 97},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[98] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 98},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[99] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 99},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[999] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 999},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    rv[9999] = LibChemist::Atom{std::array<double, 3>{0.0, 0.0, 0.0}, std::map<LibChemist::Atom::Property, double>{
      {LibChemist::Atom::Property::charge, 9999},
      {LibChemist::Atom::Property::mass, 0},
      {LibChemist::Atom::Property::cov_radius, 0.0},
      {LibChemist::Atom::Property::vdw_radius, 0.0}
    }};
    return rv;
}
} // End namespace SDE
