#include "SDE/MoleculeFileParser.hpp"
#include <sstream>
#include "SDE/NWXDefaults.hpp"
/* Warning!!!! 
 * This file was auto-generated by generate_mols.py and should not be
 * modified.  To make modifications to this file please edit
 * generate_mols.py and regenerate this file.
 */
namespace SDE {
using return_t = typename ChemistryRuntime::molecule_lut_type;
return_t default_molecules() {
    return_t rv;
    ChemistryRuntime crt{{}, {}, {}, default_atoms(),  {}, default_symbols(), {}};
    XYZParser xyz;
    std::stringstream water{
    "3"
    "Water molecule RMR stole from somewhere..."
    "H    0.000000000000000   1.579252144093028   2.174611055780858"
    "O    0.000000000000000   0.000000000000000   0.000000000000000"
    "H    0.000000000000000   1.579252144093028  -2.174611055780858"
    };
    rv["water"] = parse_molecule_file(water, xyz, crt);
    return rv;
}
} // End namespace SDE
