#include "SDE/NWXDefaults.hpp"
/* Warning!!!! 
 * This file was auto-generated by generate_basis.py and should not be
 * modified.  To make modifications to this file please edit
 * generate_basis.py and regenerate this file.
 */
namespace SDE {
using return_t = typename ChemistryRuntime::am_sym_lut_type;
return_t default_am() {
    return_t rv;
    rv["sp"] = -1;
    rv["s"] = 0;
    rv["p"] = 1;
    rv["d"] = 2;
    rv["f"] = 3;
    rv["g"] = 4;
    rv["h"] = 5;
    rv["i"] = 6;
    rv["j"] = 7;
    rv["k"] = 8;
    rv["l"] = 9;
    rv["m"] = 10;
    rv["n"] = 11;
    rv["o"] = 12;
    rv["q"] = 13;
    rv["r"] = 14;
    rv["t"] = 15;
    rv["u"] = 16;
    rv["v"] = 17;
    rv["w"] = 18;
    rv["x"] = 19;
    rv["y"] = 20;
    rv["z"] = 21;
    rv["a"] = 22;
    rv["b"] = 23;
    rv["c"] = 24;
    rv["e"] = 25;
    return rv;
}
} // End namespace SDE
