#include "SDE/NWXDefaults.hpp"
/* Warning!!!!
 * This file was auto-generated by generate_constants.py and should not be
 * modified.  To make modifications to this file please edit
 * generate_constants.py and regenerate this file.
 */
namespace SDE {
using const_t  = typename ChemistryRuntime::constant_type;
using return_t = typename ChemistryRuntime::constant_lut_type;
return_t default_constants() {
    return_t rv;
    rv["pi"] = const_t{3.14159265358979323846, "",
                       "Ratio of circle's circumference to it's diameter"};
    rv["Cal2J"] =
      const_t{4.184, "Joules per calorie", "Ratio of a Joule to a calorie"};
    rv["na"] =
      const_t{6.022140857e23, "things per mole", "Avogadro's constant"};
    rv["kb"] =
      const_t{1.38064852e-23, "Joules per Kelvin", "Boltzmann's constant"};
    rv["me"]    = const_t{9.10938356e-31, "kilograms", "Rest mass of electron"};
    rv["qe"]    = const_t{1.6021766208e-19, "Coulombs", "Charge of electron"};
    rv["alpha"] = const_t{7.2973525664e-3, "", "Fine-structure constant"};
    rv["h"]     = const_t{6.626070040e-34, "Joule seconds", "Planck constant"};
    rv["c"] =
      const_t{299792458, "meters per second", "speed of light in vacuum"};
    rv["hbar"] = const_t{1.0545718001391127e-34, "Joule seconds",
                         "Reduced Plank constant"};
    rv["e0"]   = const_t{8.854187817385606e-12, "Coulomb^2/(Joule Meter)",
                       "Vacuum permittivity"};
    rv["kc"] =
      const_t{8987551787.606497, "meter/Coulomb^2", "Coulomb's constant"};
    rv["Eh"]   = const_t{4.359744651011719e-18, "Joules", "Hartree constant"};
    rv["a0"]   = const_t{5.291772105498089e-11, "meters", "Bohr radius"};
    rv["R"]    = const_t{8.314459861448581, "Joules per Kelvin per mole",
                      "Ideal gas constant"};
    rv["Hz2J"] = const_t{6.62607004e-34, "Joules per Hertz",
                         "Conversion from Hertz to Joules"};
    rv["inv_m2J"] = const_t{1.9864458241717582e-25, "Joule meters",
                            "Conversion from m^-1 to Joules"};
    rv["eV2J"]    = const_t{6.241509125883258e+18, "Joules per eV",
                         "Conversion from eV to Joules"};
    return rv;
}
} // End namespace SDE
