#include <SDE/NWXDefaults.hpp> // Makes a non-defaulted ChemRuntime instance
#include <catch/catch.hpp>

using namespace SDE;

/*
 * CRT is basically just a giant collection of hard-coded data, testing of
 * which doesn't make any sense as the tests would be generated by the same
 * scripts used to hard-code the data.  Instead, this test focuses on making
 * sure the intended workflow works as intended.
 */
TEST_CASE("Workflow") {
    //Step 1 is always make a crt instance
    auto crt = default_runtime();

    //Step 2 is usually somehow get a molecule
    auto water = crt.pubchem.at("water");
    REQUIRE(water.atoms.size() == 3);

    //Step 3 is apply a basis set to that molecule
    auto water_w_basis = crt.apply_basis("cc-pvdz", water);

    //We just spot check a few things
    REQUIRE(water_w_basis.get_basis("cc-pvdz").size() == 24);
}
