"""
This script will turn each of the xyz files in "molecules" into the C++ commands
to make said molecule in a source file
"""

mols = ["water"]

class molecule:
    def __init__(self,name):
        self.name = name
        self.carts = []
        self.atoms = []
    def cxxify(self, f):
        f.write("    molecule {:s};\n".format(self.name))
        indent = "        "
        for i in range(len(self.atoms)):
            f.write("    {\n")
            f.write(indent + "auto temp = wikipedia.atomic_info(\"{"
                             ":s}\");\n".format(self.atoms[i]))
            f.write(indent + "temp.coord = std::array<double,3>( \n")
            f.write(indent + "    {")
            for j in range(2):
                f.write("{:s},".format(self.carts[3*i+j]))
            f.write("{:s};\n".format(self.carts[3*i+2]+'})'))
            f.write(indent + "{:s}.insert(temp);\n".format(self.name))
            f.write("    }\n")
        f.write("    rv[\"{0:s}\"] = {0:s};\n".format(self.name))

with open("../NWChemExRuntime/MoleculeRepo.cpp",'w') as f:
    f.write("#include \"NWChemExRuntime/MoleculeRepo.hpp\"\n")
    f.write("#include \"NWChemExRuntime/ReferenceDataRepo.hpp\"\n\n")
    f.write("/* This file is auto-generated by generate_mols.py.")
    f.write(" DO NOT EDIT!!!*/\n\n")
    f.write("namespace NWXRuntime {\n")
    f.write("namespace detail_ {\n\n")
    f.write("using molecule = LibChemist::SetOfAtoms;\n")
    f.write("using atom = LibChemist::Atom;\n")
    f.write("using mol_set = std::map<std::string, molecule>;\n\n")
    f.write("static mol_set default_molecules() {\n")
    f.write("    mol_set rv;\n")
    f.write("    ReferenceDataRepo wikipedia;\n")
    for m in mols:
        mol = molecule(m)
        with open("molecules/{:s}.xyz".format(m),'r') as g:
            for i,l in enumerate(g):
                if i<2:
                    continue
                line = l.split()
                mol.atoms.append(line[0])
                for j in range(1,4):
                    mol.carts.append(line[j])
        mol.cxxify(f)
    f.write("    return rv;\n}\n")
    f.write("} // End detail_\n")
    f.write("MoleculeRepo::MoleculeRepo():\n")
    f.write("  mols_(detail_::default_molecules()){}\n")
    f.write("} // End NWXRuntime \n")


