"""
This script will loop over a series of basis sets and write out a file that will
fill them in.  The format of the resulting basis sets is suitable for use with
the BasisSetExchange class
"""
import os
import re

basis_sets = ["cc-pvdz"]

new_atom = re.compile("^\s*\D{1,2}\s*0\s*$")
new_shell = re.compile("^\s*[a-zA-Z]+\s*\d+\s*1.00\s*$")
same_shell = re.compile("^\s*(?:-?\d+.\d+\s*)+$")

bases ={}

class Shell:
    def __init__(self, l):
        self.l_ = l
        self.alpha_ = []
        self.cs_ = []
    def add_prim(self, alpha, cs):
        self.alpha_.append(alpha)
        for c in cs:
            self.cs_.append(c)
    def __repr__(self):
        rv = "l : {:s} and {:d} primitives\n".format(self.l_, len(self.cs_))
        return rv

class Atom:
    def __init__(self, Z):
        self.Z_ = Z
        self.shells_ = []
    def add_shell(self, shell):
        self.shells_.append(shell)
    def __repr__(self):
        rv = "{:s} and {:d} shells".format(self.Z_, len(self.shells_))
        return rv

class BasisSet:
    def __init__(self):
        self.atoms_ = []
    def add_atom(self, atom):
        self.atoms_.append(atom)
    def get_atom(self):
        return self.atoms_[-1]
    def get_shell(self):
        return self.get_atom().shells_[-1]
    def __repr__(self):
        rv = str(self.atoms_)
        return rv

bases = {}
for bs in basis_sets:
    bases[bs] = BasisSet()
    with open(os.path.join("basis_sets",bs+".gbs"),'r') as f:
        for line in f:
            if re.search(new_atom, line):
                atom = line.split()[0]
                bases[bs].add_atom(Atom(atom))
            elif re.search(new_shell, line):
                bases[bs].get_atom().add_shell(Shell(line.split()[0]))
            elif re.search(same_shell, line):
                contents = line.split()
                bases[bs].get_shell().add_prim(contents[0],contents[1:])

def write_shell(f, shell):
    f.write("shell_t(")
    spaces = "                "
    f.write("LibChemist::ShellType::SphericalGaussian,\n")
    f.write(spaces + "LibChemist::am_str2int(\"{:s}\"),\n".format(
        shell.l_.lower()))
    f.write(spaces + "{:d},\n".format(len(shell.cs_)))
    f.write(spaces +"std::vector<double>({")
    for alpha_ in shell.alpha_:
        f.write("{:s},".format(alpha_))
    f.write("}),\n")
    f.write(spaces + "std::vector<double>({")
    for c_ in shell.cs_:
        f.write("{:s},".format(c_))
    f.write("}))")

with open(os.path.join("../NWChemExRuntime","BasisSetExchange.cpp"), 'w') as f:
    f.write("#include \"NWChemExRuntime/BasisSetExchange.hpp\"\n")
    f.write("#include \"NWChemExRuntime/AtomicInfo.hpp\"\n")
    f.write("#include <LibChemist/ShellTypes.hpp>\n\n")
    f.write("/* This file was generated by generate_basis.py. " +
            " DO NOT EDIT!!!*/\n\n")
    f.write("using input_basis_type = typename "
            "NWXRuntime::BasisSetExchange::input_basis_type;\n")
    f.write("using shell_t = LibChemist::BasisShell;")
    f.write("using shell_vector = std::vector<shell_t>;\n")
    f.write("using atomic_basis = std::map<std::size_t, shell_vector>;\n\n")
    f.write("namespace NWXRuntime{\n")
    f.write("namespace detail_ {\n")
    f.write("static auto make_basis(){\n")
    f.write("    input_basis_type bs;\n")
    for bs_name, bs in bases.items():
        bs_elem = "    bs[\"{:s}\"]".format(bs_name)
        f.write(bs_elem + " = atomic_basis();\n")
        for a in bs.atoms_:
            a_elem = "[detail_::sym2Z_.at(\"{:s}\")]".format(a.Z_.lower())
            f.write(bs_elem + a_elem+" = shell_vector();\n")
            for s in a.shells_:
                f.write(bs_elem + a_elem + ".push_back(\n        ")
                write_shell(f, s)
                f.write("\n        );\n")
    f.write("return bs;\n")
    f.write("}\n")
    f.write("}\n")
    f.write("BasisSetExchange::BasisSetExchange():\n")
    f.write("  bases_(detail_::make_basis()){}\n")
    f.write("}\n")

