#include "NWChemExRuntime/MoleculeRepo.hpp"
#include "NWChemExRuntime/ReferenceDataRepo.hpp"

/* This file is auto-generated by generate_mols.py. DO NOT EDIT!!!*/

namespace NWXRuntime {
namespace detail_ {

using molecule = LibChemist::SetOfAtoms;
using atom = LibChemist::Atom;
using mol_set = std::map<std::string, molecule>;

static mol_set default_molecules() {
    mol_set rv;
    ReferenceDataRepo wikipedia;
    molecule water;
    {
        auto temp = wikipedia.atomic_info("H");
        temp.coord = std::array<double,3>( 
            {0.000000000000000,1.579252144093028,2.174611055780858});
        water.insert(temp);
    }
    {
        auto temp = wikipedia.atomic_info("O");
        temp.coord = std::array<double,3>( 
            {0.000000000000000,0.000000000000000,0.000000000000000});
        water.insert(temp);
    }
    {
        auto temp = wikipedia.atomic_info("H");
        temp.coord = std::array<double,3>( 
            {0.000000000000000,1.579252144093028,-2.174611055780858});
        water.insert(temp);
    }
    rv["water"] = water;
    return rv;
}
} // End detail_
MoleculeRepo::MoleculeRepo():
  mols_(detail_::default_molecules()){}
} // End NWXRuntime 
